language: ruby
rvm:
  - 2.4.1
addons:
  postgresql: "9.4"
env:
  - DATABASE_URL=postgis://travis@localhost:5432/shipping_test?encoding=utf8
before_script:
  - psql -c 'CREATE DATABASE shipping_test' -U postgres
  - psql -c 'CREATE EXTENSION postgis' -U postgres -d shipping_test
script:
  - bin/rake db:create db:migrate RAILS_ENV=test
  - bin/rspec
