default: &default
  adapter:  postgis
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: prod_vnda_shipping_development

test:
  <<: *default
  database: prod_vnda_shipping_test

production:
  encoding: utf8
  pool: 15
  url: <%= ENV['DATABASE_URL'].sub(/^postgres/, "postgis") if ENV['DATABASE_URL'] %>
