default: &default
  adapter:  postgis
  encoding: unicode
  pool: 5

development:
  <<: *default
  database:  <%= ENV['DATABASE_NAME'] || "dev_vnda_shipping_development" %>

test:
  <<: *default
  database: shipping_test

production:
  encoding: utf8
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  url: <%= ENV['DATABASE_URL'].sub(/^postgres/, "postgis") if ENV['DATABASE_URL'] %>
