development: &DEVELOPMENT
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: shipping_development
  pool: 5
  username: vagrant
  password: vnda

test:
  <<: *DEVELOPMENT
  database: site_test
