development: &DEVELOPMENT
  adapter: postgis
  host: localhost
  encoding: unicode
  database: shipping_development
  username: postgres
  
  pool: 5

test: &DEVELOPMENT
  adapter: postgis
  host: localhost
  encoding: unicode
  database: shipping_test
  username: postgres
  
  pool: 5
