development: &DEVELOPMENT
  adapter: postgis
  host: localhost
  encoding: unicode
  database: shipping_development
  username: vagrant
  password: vnda
  pool: 5

test:
  <<: *DEVELOPMENT
  database: shipping_test

production:
  url: <%= ENV['DATABASE_URL'].sub(/^postgres/, "postgis") if ENV['DATABASE_URL'] %>
