development: &DEVELOPMENT
  adapter: postgis
  host: localhost
  encoding: unicode
  database: shipping_development
  
  pool: 5

test: &DEVELOPMENT
  adapter: postgis
  host: localhost
  encoding: unicode
  database: shipping_test
  
  pool: 5

production:
  url: <%= ENV['DATABASE_URL'].sub(/^postgres/, "postgis") if ENV['DATABASE_URL'] %>